# Generated by Django 2.1.2 on 2018-10-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20181027_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='images',
        ),
        migrations.AddField(
            model_name='studentimagedetails',
            name='binusianId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='attendance.Student'),
            preserve_default=False,
        ),
    ]
