# Generated by Django 2.1.2 on 2018-11-01 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20181101_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginDate', models.DateField()),
                ('loginTime', models.TimeField()),
                ('classScheduleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.ClassSchedule')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student')),
            ],
        ),
    ]
