# Generated by Django 2.1.2 on 2018-11-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancedata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.RenameField(
            model_name='classschedule',
            old_name='endDate',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='startDate',
        ),
    ]
